name: ncov_paraFix
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ipykernel
  - notebook
  - biopython
  - pandas
  - matplotlib
  - matplotlib-venn
  - muscle
  - hyphy
  - r-languageserver
  - r-phangorn
  - r-jsonlite
  - r-svglite
  - bioconductor-sitepath